spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:}:${DB_PORT:}/ocb_nghia?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

weather:
  api:
    key: ${WEATHER_API_KEY}