spring:
  application:
    name: weather_info
  config:
    import: "classpath.file:./application-secret.yml"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

weather:
  fetch:
    interval: 300000

